### ISSUE TITLE
FileDownloader.startForeground() equivalent function

### ISSUE THREAD

**Issue by xCalifier** [lingochamp/okdownload#19]
What is the equivalent function for FileDownloader.startForeground() function, i could not find any method equivalent to it in javadoc.

Moreover a lot of people are using FileDownloader, it will be a very good step to maintain a porting guide with equivalent functions.

**Comment by Jacksgong** [comment]
Actually, for more simpleness, okdownload core library doesn't run on the service, it's just an `okdownload` singleton (what is like `OkHttpClient` or `Picasso` provided), so there isn't `startForeground` now.

Then, if you want okdownload running in the service now because you want to get the benefit from foreground service, you just feel free to create a service and download resource with okdownload on it.

#### On More Thing

On the further version, we will implement a special `DownloadDispatcher` to implement okdownload running on the independent process, then you can enable it like `okdownload:sqlite` or `okdownload:okhttp` which has been said on [here](https://github.com/lingochamp/okdownload/wiki/Advanced-Use-Guideline#ii-injection-component), and on that moment, I think we will provide such `startForeground` method again.
