### ISSUE TITLE
Add a new status in StatusUtil.Status

### ISSUE THREAD

**Issue by janbolat** [lingochamp/okdownload#29]
Hi,
Please add a FAILED status or a CANCELED status in StatusUtil.
Thank you.

// I am using sqlite for storing breakpoints

**Comment by Jacksgong** [comment]
For the purer, we don't store status in the store again, as you know the current store is named `BreakpointStore`, and the atom info is named `BreakpointInfo` since the data is only used for resume from the breakpoint. So we can know whether the task is launched, but don't know whether the task is failed or not.

---

But we remain the interface which can touch the final status when a task is ended, you can find it on `DownloadStore#onTaskEnd`.
