### ISSUE TITLE
Persist state

### ISSUE THREAD

**Issue by duncanokeyo** [lingochamp/okdownload#63]
ok, i have managed to run the sample app in my phone and its working as stated... But when i rotate the screen, the progress bar, parcentage of download are reset, so i cannot trace the progress of the download....

How can i get the progress of downloads when there is orientation change in the phone..
Thank you

**Comment by Jacksgong** [comment]
So I think your problem is following:

### 1. Sample project reset percentage of download after rotate screen?

It's not exactly.  Such as `SingleActivity`, if you rotate the screen, the lifecycle of Activity will invoke `onDestroy` and then invoke `onCreate`, so when `onDestory` is invoked, the task would be canceled:

```java
@Override protected void onDestroy() {
    super.onDestroy();
    if (task != null) task.cancel();
}
```

And when the `onCreate` is invoked, the current percentage of the download will be got and displayed:

```java
@Override protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_single);
    initSingleDownload(
            (TextView) findViewById(R.id.statusTv),
            (ProgressBar) findViewById(R.id.progressBar),
            findViewById(R.id.actionView),
            (TextView) findViewById(R.id.actionTv));
}

private void initSingleDownload(TextView statusTv, ProgressBar progressBar, View actionView,
                                TextView actionTv) {
    initTask();
    // on this method will get current percentage of the download and assign to the progress bar.
    initStatus(statusTv, progressBar);
    initAction(actionView, actionTv, statusTv, progressBar);
}
```

### 2. How to get the progress of downloads

1. You can just see the `initStatus` method on the `SingleActivity` and get the way
2. Please move to [wiki](https://github.com/lingochamp/okdownload/wiki/Simple-Use-Guideline#2-get-breakpointinfo-beyond-listener)
